@startuml
class Impuesto {
-monto: BigDecimal

}

class Contribuyente {
-nombre: String
-cuil: String

}

class Calculadora {
+calcular(impuesto: Impuesto):void

}
Impuesto "1" --> "1" Contribuyente
Calculadora ..> Impuesto : <<use>>
@enduml